### ISSUE TITLE
Single page improvements

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/seek#13]
In the left side section
- horizontal scrollable bar
- vertical scrollable bar
- show all items collapsed by default?
- "collapse all investigations" option somewhere
- "View more" button when there are too many Investigations

**Comment by rabuono** [comment]
Would be nice to have a "collapse all studies" and a "collapse all assays" also.

**Comment by vdk88** [comment]
I think having the Investigation/Study/Assay toggling option will solve some of the problems.
Horizontal scrollbar and toggling option have been added anyway.
