### ISSUE TITLE
Templates listed in alphabetical order in "choose a template" drop down menu

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#14]
The repository Templates are being listed in alphabetical order in the `Choose a template` menu when creating a Study.
They should be listed according to the `"group_order":` listed in their metadata.
![image](https://user-images.githubusercontent.com/77321541/156152878-c90818b1-296c-4918-8e1f-7f6b72dcc7f9.png)

**Comment by vdk88** [comment]
Fixed

**Comment by floradanna** [comment]
I don't see this fixed in datahub.dev yet. Are you working locally?

**Comment by rabuono** [comment]
Also not fixed for me

**Comment by rabuono** [comment]
I see it fixed now
Thanks!
