### ISSUE TITLE
Error when deleting assay

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/seek#16]
Assay n2 in a Study
- Assay design --> Samples: no samples shown
- Assay design --> Table: samples **are shown**
- No SOP associates

Assay --> Actions --> Delete assay: it gives error (This is not a secure form and http://0.0.0.0:3002/assays/15?return_to=%2Fsingle_pages%2F9)

Screenshots of the error:
![Screenshot 2022-03-02 at 16 38 51](https://user-images.githubusercontent.com/51486716/156395107-2ebd540e-43db-4910-9932-a6bc7a516140.png)
![Screenshot 2022-03-02 at 16 39 03](https://user-images.githubusercontent.com/51486716/156395116-183aefa8-6e80-4fcf-a615-a1ffe5b33819.png)

**Comment by floradanna** [comment]
Not being able to delete the assay "root gene expression" could be due to the fact that a sample type (n 33) is still associated with the assay. How to solve that?

**Comment by vdk88** [comment]
This is because the application uses the local server address. This is not basically an issue since it will be fine in the production server.
