### ISSUE TITLE
Wrong Sample Type used for Input

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#17]
In the following [project](https://datahub.dev.elixir-belgium.org/single_pages/10)
`Input` for Assay `sequencing step` (purple arrow) should be from `library step`, but it is from the `Extraaction` Assay (red arrow).

![image](https://user-images.githubusercontent.com/77321541/156167764-06babf2a-0922-4861-a7a7-3e066640629e.png)

**Comment by rabuono** [comment]
Tried again in this Project.
Same effect.
Using the `create the next Assay` button in the 3rd or 4th Assay has as default the 2nd Assay in the `Input Assay` drop down menu (clipping below).
![image](https://user-images.githubusercontent.com/77321541/156374985-ea0d1e73-7158-4a8d-80c2-368b9ccd8c2a.png)

**Comment by vdk88** [comment]
Fixed
