### ISSUE TITLE
Remove values from keys normaly used for data repositories in study in ISAjson export 

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#18]
- [x] The [`identifier` in the study](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L39) can be used to have accession numbers of data repositories.

- [x] The[ submissionDate ](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L42)is also generally used to refer to the submission to a data repository

- [x] The [publicReleasDate](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L43) is also generally used to refer to the public release in a data repository

We might want to leave these empty for now and not store SEEK study numbers there.

**Comment by rabuono** [comment]
A `comments` object can be added to the study so that the SEEK information about the study can be recorded.
As described in the [schema](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L44)

**Comment by vdk88** [comment]
Fixed

**Comment by rabuono** [comment]
Added independent issue for having `comments` with SEEK information for studies
Issue #33
