### ISSUE TITLE
Add study filename to ISAjson export

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#19]
The [study filename](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L44) can be populated by the name given by the user to the Study in SEEK. Following the pattern s_StudyNameByUser.txt

**Comment by floradanna** [comment]
In some documentation, it seems that also Investigation needs a filename: i_InvestigationNameByUser.txt. We could obtained by using the "title": i_title.txt and s_title.txt.

For assay title (a_title.txt), we need to have "stream" or "experiment" (group of assays) first or come up with temporary solution.

**Comment by rabuono** [comment]
Agreed.
The SEEK Title given by the user for both Investigation and Study can be used to name the files.

Also agreed with having a temporary solution for Assay, until we get the possibility of having streams.
For now `a_assays.txt` might be sufficient.

**Comment by vdk88** [comment]
Fixed

**Comment by vdk88** [comment]
Fixed
