### ISSUE TITLE
Not all source_characteristic are being added in Source in ISAjson export

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#20]
The Attributes tagged as  `source_characteristic` seem to making their way into the studies [`characteristicCategories`](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L74) but are not all used in the [`characteristics` object](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L153) in `source`. All of the `source_characteristics` attributes used to describe a `source` should appear in the `characteristics` of that `source`.
Example from [this Project](https://datahub.dev.elixir-belgium.org/single_pages/10)

**Comment by floradanna** [comment]
I can reproduce the issue also for other project. Not all the listed `Study` `characteristicCategories` are re-used under `materials` --> `sources` -->`characteristics` --> `category` for each source.

**Comment by floradanna** [comment]
> Do you mean all the items under `characteristicCategories` should appear under `materials` --> `sources` -->`characteristics` --> `category` ? 

Yes. This first option.
In `Study` `characteristicCategories` all Study's attributes are listed. Then, `characteristicCategories` referred to sources go to `materials` --> `sources `--> `characteristics` --> `category` where the attributes' value for each source is given.
Same for `samples`.

**Comment by rabuono** [comment]
Seems to work for me now with `sources`. All the listed `source_characteristics` are now being used as characteristics of that source
