### ISSUE TITLE
In ISAjson export the protocol used at the sample collection is not declared in the protocols object

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#21]
The [protocol used](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L226) in the `processSequence` to convert a `Source` to a `Sample` is not declared in the [`protocols` object](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L267).

Example from [this Project](https://datahub.dev.elixir-belgium.org/single_pages/10)

**Comment by floradanna** [comment]
I can reproduce the issue in other project. "Sample collection" protocol is not listed in Study `protocols`.

**Comment by vdk88** [comment]
Fixed
