### ISSUE TITLE
In ISAjson export a unit @id is being used despite no units being declared

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#22]
A unit `@id` value is being given in multiple places ([example here](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L735)) despite no units being declared in [`unitCategories`](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L1192).
Example from [this Project](https://datahub.dev.elixir-belgium.org/single_pages/10)

Note: At this point there is no way to add units to any of the attributes in the dynamic table. So there are not units to declare. The error might be on generating values for the `@id` of units when no units are rightfully not declared.

**Comment by vdk88** [comment]
All the related ids are no longer being created by the exporter.
