### ISSUE TITLE
DataHub Assays are being exported as independent Assays in ISAjson export

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#23]
As there are no Streams in the current implementation, all the DataHub Assays belonging to a Study are to be combined into a single Assay in the ISAjson export in the [`assays` object](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L413).
Each DataHub Assay corresponds to a step in the `processSequence` in that ISAjson Assay.

**Comment by vdk88** [comment]
Fixed

**Comment by vdk88** [comment]
The Assays seem combined. But there is some potentially weird nesting.
[Here](https://github.com/rabuono/ISA-merger/blob/ff8034167e63a114ffac7b395193afa54225e0a8/ISAjson_exports/20220411_isa_Investigationation_2.json#L596) is an example of what I mean.
The otherMaterials that come from different SEEK Assays are being nested inside []
