### ISSUE TITLE
In ISAjson export the declared protocol @id in protocols is not the one used in processSequence

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#24]
The `@id` values declared for each protocol in `protocols` does not match the ones being used in `processSequence`.

[Example at `protocols`](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L269)
[Same at `processSequence`](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L496)

Example from [this Project](https://datahub.dev.elixir-belgium.org/single_pages/10)

**Comment by vdk88** [comment]
Fixed
