### ISSUE TITLE
In ISAjson export the @id of an assay should not reflect the SEEK ID of a single SEEK Assay

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#25]
Considering issue #23 , the value for an ISAjson Assay's `@id` cannot be the SEEK ID of a single SEEK Assay.
[Example of an Assay `@id` in the current ISAjson export](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L415)
Example from [this Project](https://datahub.dev.elixir-belgium.org/single_pages/10)

A solution might be to concatenate the SEEK IDs of all SEEK Assays that make up that ISAjson Assay.
For an ISAjson Assay that is made by SEEK Assays 13, 14, and 15, the `@id` would look like: `"@id": "#assay/13_14_15",`

**Comment by vdk88** [comment]
Fixed
