### ISSUE TITLE
In ISAjson export otherMaterials objects are being referenced as samples

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#26]
A `otherMaterial` [here](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L440) is referenced in [`samples`](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L628) with an non-existing sample prefix [here](https://github.com/rabuono/ISA-merger/blob/1ba420c76c8874ad3fbc7c402152053fe0770c2e/ISAjson_exports/20220302_isa_Investigationation_1.json#L630).
It should not be in the `samples` object and should be called by its original otherMaterial `@id`

**Comment by vdk88** [comment]
Fixed

**Comment by rabuono** [comment]
The `@id` of `other_material` is inconsistent.
Example from [this project](https://datahub.dev.elixir-belgium.org/single_pages/10)
In `otherMaterials`: `Extracting 1a` is given [`"@id": "#material/323"`](https://github.com/rabuono/ISA-merger/blob/ac57a6cec355b6d82681f3a328dd10fcd33aac16/ISAjson_exports/20220415_isa_Investigationation_1.json#L586)
But is then, referenced as `#other_material/51` [here](https://github.com/rabuono/ISA-merger/blob/ac57a6cec355b6d82681f3a328dd10fcd33aac16/ISAjson_exports/20220415_isa_Investigationation_1.json#L659), [here](https://github.com/rabuono/ISA-merger/blob/ac57a6cec355b6d82681f3a328dd10fcd33aac16/ISAjson_exports/20220415_isa_Investigationation_1.json#L771), and [here](https://github.com/rabuono/ISA-merger/blob/ac57a6cec355b6d82681f3a328dd10fcd33aac16/ISAjson_exports/20220415_isa_Investigationation_1.json#L814).
And, finally, as `#otherMaterials/51` [here](https://github.com/rabuono/ISA-merger/blob/ac57a6cec355b6d82681f3a328dd10fcd33aac16/ISAjson_exports/20220415_isa_Investigationation_1.json#L948) and [here](https://github.com/rabuono/ISA-merger/blob/ac57a6cec355b6d82681f3a328dd10fcd33aac16/ISAjson_exports/20220415_isa_Investigationation_1.json#L1150).

The unique `@id` declared in `otherMaterials` should be reused in all other references.
