### ISSUE TITLE
In ISAjson export value for characteristics in second SEEK Assay are not being added

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#32]
Example from [this project](https://datahub.dev.elixir-belgium.org/single_pages/10)

In the `assays` object in the ISAjson.
Under `otherMaterials`
The `characteristics` `value` are being filled with the Attribute Title and not the Attribute value for that SEEK Sample.
Example [here](https://github.com/rabuono/ISA-merger/blob/5872033ea138e4b3d31ddb7fabc929b3f9ab4661/ISAjson_exports/20220404_isa_Investigationation_1.json#L727)

The values `Title`, `submission date`, `status`, and `accession` are actually the Titles for the Attributes (or the `characteristicType` `annotationValue`, example [here](https://github.com/rabuono/ISA-merger/blob/5872033ea138e4b3d31ddb7fabc929b3f9ab4661/ISAjson_exports/20220404_isa_Investigationation_1.json#L677)). In this example, the characteristic `Title` has values input by user, while `submission date`, `status`, and `accession` have no values input.

**Comment by vdk88** [comment]
Fixed

**Comment by rabuono** [comment]
After the change the [`@id` being referenced in `"category"`](https://github.com/rabuono/ISA-merger/blob/ff8034167e63a114ffac7b395193afa54225e0a8/ISAjson_exports/20220411_isa_Investigationation_2.json#L605) does not match the [declared `@id` of the characteristic](https://github.com/rabuono/ISA-merger/blob/ff8034167e63a114ffac7b395193afa54225e0a8/ISAjson_exports/20220411_isa_Investigationation_2.json#L531)

**Comment by vdk88** [comment]
Fixed
