### ISSUE TITLE
In ISAjson export add Project name and Project SEEK ID as a comment in Investigation

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#34]
Currently the exported ISAjson carries no information about which SEEK Project that Investigation belongs to.
That information can be added to the same `comments` object in `investigation` as the `ISAjson export time` is currently held.
[Example here](https://github.com/rabuono/ISA-merger/blob/9ba37e7149fd4e61a801d03bec7f43610f97fee7/ISAjson_exports/20220411_AE_investigation_1isa.json#L17).

A couple of comments can be added:
`"name": "SEEK Project name` with `"value":` being the name of the Project to which the Investigation is associated with
`"name": "SEEK Project ID` with `"value":` being the SEEK ID for the Project to which the Investigation is associated with

**Comment by vdk88** [comment]
Fixed
