### ISSUE TITLE
In ISAjson export the @id of equally named attributes are not unique

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#38]
In an Investigation, if two attributes with isaTag `other_material_characteristic` have the same attribute title, they end up receiving the same `@id` in the ISAjson export. This causes the `@id` to not be unique.

An example from [this project](https://datahub.dev.elixir-belgium.org/single_pages/15).
`#characteristic_category/status` appears three times: [here](https://github.com/rabuono/ISA-merger/blob/fcb90127781e84e3b7d3a71cdc66de9cf3ad7379/ISAjson_exports/20220415_isa_Inv_repetitive_2.json#L161), [here](https://github.com/rabuono/ISA-merger/blob/fcb90127781e84e3b7d3a71cdc66de9cf3ad7379/ISAjson_exports/20220415_isa_Inv_repetitive_2.json#L634) and [here](https://github.com/rabuono/ISA-merger/blob/fcb90127781e84e3b7d3a71cdc66de9cf3ad7379/ISAjson_exports/20220415_isa_Inv_repetitive_2.json#L666).
These reflect an attribute of title `status` in the Source table and in two SEEK Assays.

**Comment by vdkkia** [comment]
We can use the attribute id at for create the @id

**Comment by vdkkia** [comment]
We should create such an @id for all **characteristic_category** items
