### ISSUE TITLE
In ISAjson export the @id used in processSequence is sometimes incomplete

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#40]
The `@id` in [`previousProcess`](https://github.com/rabuono/ISA-merger/blob/fcb90127781e84e3b7d3a71cdc66de9cf3ad7379/ISAjson_exports/20220415_isa_Inv_repetitive_2.json#L907) and [`derivedProcess`](https://github.com/rabuono/ISA-merger/blob/fcb90127781e84e3b7d3a71cdc66de9cf3ad7379/ISAjson_exports/20220415_isa_Inv_repetitive_2.json#L910) are incomplete in comparison to the [originally declared `@id`](https://github.com/rabuono/ISA-merger/blob/fcb90127781e84e3b7d3a71cdc66de9cf3ad7379/ISAjson_exports/20220415_isa_Inv_repetitive_2.json#L850).

**Comment by vdkkia** [comment]
> @rabuono: I think for process we can do the name of the protocol being applied + a number. So every process that applies the same protocol has a similar name (easier for humans), but has a unique number at the end (keeping the unique ID requirement).
> Without testing, I assume one can add the Sample SEEK ID number of the resulting SEEK Sample for that process. But I don't think this is necessary and that just incremental numbers would already solve the problem.

The name of the applied protocol + SEEK sample ID has been used
