### ISSUE TITLE
In ISAjson export not all source characteristic are being exported

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#44]
From [Project 17](https://datahub.dev.elixir-belgium.org/single_pages/17)
'Source Characteristic 3` is not being exported to the ISAjson. 

['Source Characteristic 2'](https://github.com/rabuono/ISA-merger/blob/c625fc7f87a622763c8befd7530db95be35266a3/ISAjson_exports/20220502_ISA_export_test_1_Investigation_1_a_isa.json#L172) and ['Source Characteristic 1'](https://github.com/rabuono/ISA-merger/blob/c625fc7f87a622763c8befd7530db95be35266a3/ISAjson_exports/20220502_ISA_export_test_1_Investigation_1_a_isa.json#L180) are exported.

**Comment by floradanna** [comment]
From [SEEK project 16](https://datahub.dev.elixir-belgium.org/single_pages/16)
- Source Characteristic 3 is missing in [studies --> characteristicCategories](https://github.com/floradanna/ISA-merger/blob/6ebba15a56657b8e873762f0f8220d11b1aceabe/isa_export/20220502_isa-15.json#L155) and in [materials --> sources](https://github.com/floradanna/ISA-merger/blob/6ebba15a56657b8e873762f0f8220d11b1aceabe/isa_export/20220502_isa-15.json#L182)
- Source Characteristic 1 and 2 are exported correctly instead.

**Comment by vdkkia** [comment]
After some investigation, it turned out the attribute is not well-defined in the aggregated template JSON file [here](https://github.com/ELIXIR-Belgium/ISA-merger/blob/0e56320353d5386bc832df88f7850d15c5d01fbe/templates/isa%20test/isa_test_aggregated_v1.0.0.json#L60).
