### ISSUE TITLE
In ISAjson export Ontology listed for values for attribute is being added as attribute PID

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/seek#45]
From [Project 17](https://datahub.dev.elixir-belgium.org/single_pages/17)

For [sample characteristic 3](https://github.com/rabuono/ISA-merger/blob/c625fc7f87a622763c8befd7530db95be35266a3/ISAjson_exports/20220502_ISA_export_test_1_Investigation_1_a_isa.json#L206) the Ontology is about the attribute values (marked in purple below), but it is being listed as the definitions of the Attribute Title (PID, marked in yellow below).

The same mistake is made for the `characteristicCategories` of `assays`. [Example here](https://github.com/rabuono/ISA-merger/blob/c625fc7f87a622763c8befd7530db95be35266a3/ISAjson_exports/20220502_ISA_export_test_1_Investigation_1_a_isa.json#L926) in which all of the listed Ontology sources are in reality for the values of the attributes and not for the titles.

![image](https://user-images.githubusercontent.com/77321541/166228657-6f27329b-f636-4eed-a8d2-5f854cc3f5cf.png)

**Comment by rabuono** [comment]
The same problem applies to 'parameters'. The Ontology to be used for the accepted values is being listed as the SEEK Attribute Title PID. [Example here](https://github.com/rabuono/ISA-merger/blob/c625fc7f87a622763c8befd7530db95be35266a3/ISAjson_exports/20220502_ISA_export_test_1_Investigation_1_a_isa.json#L480)

**Comment by rabuono** [comment]
New export shows the same problem.
[1st example here](https://github.com/rabuono/ISA-merger/blob/349fea78b7a7292d26824e0292712cb9afb94a8a/ISAjson_exports/20220515_ISA_export_test_1_Investigation_1_a_isa.json#L204)
[2nd example here](https://github.com/rabuono/ISA-merger/blob/349fea78b7a7292d26824e0292712cb9afb94a8a/ISAjson_exports/20220515_ISA_export_test_1_Investigation_1_a_isa.json#L1044)
[3rd example here](https://github.com/rabuono/ISA-merger/blob/349fea78b7a7292d26824e0292712cb9afb94a8a/ISAjson_exports/20220515_ISA_export_test_1_Investigation_1_a_isa.json#L544)
Examples of an ontology root term to be used for input values being used for defining the Attribute title.

**Comment by floradanna** [comment]
Urgent. To be fixed as priority.

**Comment by floradanna** [comment]
To clarify: if `pid` in `sample_attributes` table (coming from `iri` in `template_attributes` table) of the particular `sample_attribute` is empty, there **shouldn't** be any data for `termSource `and `termAccession` in the **"characteristicCategories"** section of the exported ISA-JSON file.

Related to issue https://github.com/seek4science/seek/issues/1010
