### ISSUE TITLE
Add SEEK sample ID in CSV export (enhancement)

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/seek#49]
SEEK sample ID could be shown in a column that precedes the Material column (xxx Name) in CSV export. Example below.

<img width="806" alt="Screenshot 2022-05-02 at 15 38 24" src="https://user-images.githubusercontent.com/51486716/166243432-5824728f-57f4-4998-9175-a1f9600109ec.png">

<img width="1325" alt="Screenshot 2022-05-02 at 15 40 15" src="https://user-images.githubusercontent.com/51486716/166243443-3d879e7f-95d7-40ef-882f-f36e1c31023b.png">

**Comment by rabuono** [comment]
I was wondering if providing the SEEK Sample IDs with the full URL wouldn't be better. This way it also provides information about which instance that Sample CSV export is coming from.
