### ISSUE TITLE
About datahub page must be updated

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/seek#60]
The About DataHub page from our instances must be updated: delete the sentence "The better way to manage your data is coming"

**Comment by floradanna** [comment]
@floradanna @kdp-cloud

**Comment by kdp-cloud** [comment]
Done.
![image](https://github.com/ELIXIR-Belgium/seek/assets/82407142/41d2942c-cf73-4126-9a70-33378e84f3de)
