### ISSUE TITLE
Edit the Integrations image in landing page before login

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/seek#61]
@kdp-cloud  In datahub landing page before login, remove the icons that are not applicable to DataHub from the integrations image (see below)

![Screenshot 2024-04-19 at 10 53 23](https://github.com/ELIXIR-Belgium/seek/assets/51486716/f3f36fef-bd5b-491d-9ec9-6d13b786de8d)

**Comment by kdp-cloud** [comment]
@floradanna I left Zenodo in there for now.
![image](https://github.com/ELIXIR-Belgium/seek/assets/82407142/ad922761-94b5-45b6-b7d1-1c3e82a487d8)

**Comment by floradanna** [comment]
remove alse Zenodo (not enabled for now)

**Comment by kdp-cloud** [comment]
When Zenodo publishing is disabled:
![image](https://github.com/ELIXIR-Belgium/seek/assets/82407142/1e451bd9-9c1f-4be8-a8c3-46416b74c0fd)

When Zenodo publishing is enabled:
![image](https://github.com/ELIXIR-Belgium/seek/assets/82407142/94cf6bdf-a436-438d-a0a6-1ed5905271f9)
